window.esdocSearchIndex = [
  [
    "svelte-extend/src/services/extender.js~extender",
    "class/src/services/extender.js~Extender.html",
    "<span>Extender</span> <span class=\"search-result-import-path\">svelte-extend/src/services/extender.js</span>",
    "class"
  ],
  [
    "svelte-extend/src/services/jsmerger.js~jsmerger",
    "class/src/services/jsMerger.js~JSMerger.html",
    "<span>JSMerger</span> <span class=\"search-result-import-path\">svelte-extend/src/services/jsMerger.js</span>",
    "class"
  ],
  [
    "svelte-extend/src/services/sfcdata.js~sfcdata",
    "class/src/services/sfcData.js~SFCData.html",
    "<span>SFCData</span> <span class=\"search-result-import-path\">svelte-extend/src/services/sfcData.js</span>",
    "class"
  ],
  [
    "svelte-extend/src/services/sfcparser.js~sfcparser",
    "class/src/services/sfcParser.js~SFCParser.html",
    "<span>SFCParser</span> <span class=\"search-result-import-path\">svelte-extend/src/services/sfcParser.js</span>",
    "class"
  ],
  [
    "svelte-extend/src/app/index.js~svelteextend",
    "class/src/app/index.js~SvelteExtend.html",
    "<span>SvelteExtend</span> <span class=\"search-result-import-path\">svelte-extend/src/app/index.js</span>",
    "class"
  ],
  [
    "svelte-extend/src/rollup.js~svelteextendrollupplugin",
    "class/src/rollup.js~SvelteExtendRollupPlugin.html",
    "<span>SvelteExtendRollupPlugin</span> <span class=\"search-result-import-path\">svelte-extend/src/rollup.js</span>",
    "class"
  ],
  [
    "svelte-extend/src/services/extender.js~extender",
    "variable/index.html#static-variable-extender",
    "<span>extender</span> <span class=\"search-result-import-path\">svelte-extend/src/services/extender.js</span>",
    "variable"
  ],
  [
    "svelte-extend/src/services/jsmerger.js~jsmerger",
    "variable/index.html#static-variable-jsMerger",
    "<span>jsMerger</span> <span class=\"search-result-import-path\">svelte-extend/src/services/jsMerger.js</span>",
    "variable"
  ],
  [
    "svelte-extend/src/services/sfcdata.js~sfcdata",
    "variable/index.html#static-variable-sfcData",
    "<span>sfcData</span> <span class=\"search-result-import-path\">svelte-extend/src/services/sfcData.js</span>",
    "variable"
  ],
  [
    "svelte-extend/src/services/sfcparser.js~sfcparser",
    "variable/index.html#static-variable-sfcParser",
    "<span>sfcParser</span> <span class=\"search-result-import-path\">svelte-extend/src/services/sfcParser.js</span>",
    "variable"
  ],
  [
    "svelte-extend/src/webpack.js~svelteextendwebpackloader",
    "function/index.html#static-function-svelteExtendWebpackLoader",
    "<span>svelteExtendWebpackLoader</span> <span class=\"search-result-import-path\">svelte-extend/src/webpack.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/app/index.js",
    "file/src/app/index.js.html",
    "src/app/index.js",
    "file"
  ],
  [
    "src/app/index.js~svelteextend#extend",
    "class/src/app/index.js~SvelteExtend.html#instance-method-extend",
    "src/app/index.js~SvelteExtend#extend",
    "method"
  ],
  [
    "src/app/index.js~svelteextend#extendfrompath",
    "class/src/app/index.js~SvelteExtend.html#instance-method-extendFromPath",
    "src/app/index.js~SvelteExtend#extendFromPath",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/rollup.js",
    "file/src/rollup.js.html",
    "src/rollup.js",
    "file"
  ],
  [
    "src/rollup.js~rollupfilter",
    "typedef/index.html#static-typedef-RollupFilter",
    "src/rollup.js~RollupFilter",
    "typedef"
  ],
  [
    "src/rollup.js~svelteextendrollupplugin#constructor",
    "class/src/rollup.js~SvelteExtendRollupPlugin.html#instance-constructor-constructor",
    "src/rollup.js~SvelteExtendRollupPlugin#constructor",
    "method"
  ],
  [
    "src/rollup.js~svelteextendrollupplugin#name",
    "class/src/rollup.js~SvelteExtendRollupPlugin.html#instance-get-name",
    "src/rollup.js~SvelteExtendRollupPlugin#name",
    "member"
  ],
  [
    "src/rollup.js~svelteextendrollupplugin#options",
    "class/src/rollup.js~SvelteExtendRollupPlugin.html#instance-get-options",
    "src/rollup.js~SvelteExtendRollupPlugin#options",
    "member"
  ],
  [
    "src/rollup.js~svelteextendrollupplugin#transform",
    "class/src/rollup.js~SvelteExtendRollupPlugin.html#instance-method-transform",
    "src/rollup.js~SvelteExtendRollupPlugin#transform",
    "method"
  ],
  [
    "src/rollup.js~svelteextendrollupplugin.svelteextend",
    "class/src/rollup.js~SvelteExtendRollupPlugin.html#static-method-svelteExtend",
    "src/rollup.js~SvelteExtendRollupPlugin.svelteExtend",
    "method"
  ],
  [
    "src/rollup.js~svelteextendrolluppluginoptions",
    "typedef/index.html#static-typedef-SvelteExtendRollupPluginOptions",
    "src/rollup.js~SvelteExtendRollupPluginOptions",
    "typedef"
  ],
  [
    "src/services/extender.js",
    "file/src/services/extender.js.html",
    "src/services/extender.js",
    "file"
  ],
  [
    "src/services/extender.js~extender#constructor",
    "class/src/services/extender.js~Extender.html#instance-constructor-constructor",
    "src/services/extender.js~Extender#constructor",
    "method"
  ],
  [
    "src/services/extender.js~extender#generate",
    "class/src/services/extender.js~Extender.html#instance-method-generate",
    "src/services/extender.js~Extender#generate",
    "method"
  ],
  [
    "src/services/index.js",
    "file/src/services/index.js.html",
    "src/services/index.js",
    "file"
  ],
  [
    "src/services/jsmerger.js",
    "file/src/services/jsMerger.js.html",
    "src/services/jsMerger.js",
    "file"
  ],
  [
    "src/services/jsmerger.js~jsmerger#mergecode",
    "class/src/services/jsMerger.js~JSMerger.html#instance-method-mergeCode",
    "src/services/jsMerger.js~JSMerger#mergeCode",
    "method"
  ],
  [
    "src/services/sfcdata.js",
    "file/src/services/sfcData.js.html",
    "src/services/sfcData.js",
    "file"
  ],
  [
    "src/services/sfcdata.js~sfcdata#addbasefiledata",
    "class/src/services/sfcData.js~SFCData.html#instance-method-addBaseFileData",
    "src/services/sfcData.js~SFCData#addBaseFileData",
    "method"
  ],
  [
    "src/services/sfcdata.js~sfcdata#addmarkup",
    "class/src/services/sfcData.js~SFCData.html#instance-method-addMarkup",
    "src/services/sfcData.js~SFCData#addMarkup",
    "method"
  ],
  [
    "src/services/sfcdata.js~sfcdata#addscript",
    "class/src/services/sfcData.js~SFCData.html#instance-method-addScript",
    "src/services/sfcData.js~SFCData#addScript",
    "method"
  ],
  [
    "src/services/sfcdata.js~sfcdata#addstyle",
    "class/src/services/sfcData.js~SFCData.html#instance-method-addStyle",
    "src/services/sfcData.js~SFCData#addStyle",
    "method"
  ],
  [
    "src/services/sfcdata.js~sfcdata#basefiledata",
    "class/src/services/sfcData.js~SFCData.html#instance-get-baseFileData",
    "src/services/sfcData.js~SFCData#baseFileData",
    "member"
  ],
  [
    "src/services/sfcdata.js~sfcdata#constructor",
    "class/src/services/sfcData.js~SFCData.html#instance-constructor-constructor",
    "src/services/sfcData.js~SFCData#constructor",
    "method"
  ],
  [
    "src/services/sfcdata.js~sfcdata#directory",
    "class/src/services/sfcData.js~SFCData.html#instance-get-directory",
    "src/services/sfcData.js~SFCData#directory",
    "member"
  ],
  [
    "src/services/sfcdata.js~sfcdata#extendtagattributes",
    "class/src/services/sfcData.js~SFCData.html#instance-get-extendTagAttributes",
    "src/services/sfcData.js~SFCData#extendTagAttributes",
    "member"
  ],
  [
    "src/services/sfcdata.js~sfcdata#filepath",
    "class/src/services/sfcData.js~SFCData.html#instance-get-filepath",
    "src/services/sfcData.js~SFCData#filepath",
    "member"
  ],
  [
    "src/services/sfcdata.js~sfcdata#hasbasefiledata",
    "class/src/services/sfcData.js~SFCData.html#instance-get-hasBaseFileData",
    "src/services/sfcData.js~SFCData#hasBaseFileData",
    "member"
  ],
  [
    "src/services/sfcdata.js~sfcdata#hasmodulescripts",
    "class/src/services/sfcData.js~SFCData.html#instance-get-hasModuleScripts",
    "src/services/sfcData.js~SFCData#hasModuleScripts",
    "member"
  ],
  [
    "src/services/sfcdata.js~sfcdata#hasscripts",
    "class/src/services/sfcData.js~SFCData.html#instance-get-hasScripts",
    "src/services/sfcData.js~SFCData#hasScripts",
    "member"
  ],
  [
    "src/services/sfcdata.js~sfcdata#hasstyles",
    "class/src/services/sfcData.js~SFCData.html#instance-get-hasStyles",
    "src/services/sfcData.js~SFCData#hasStyles",
    "member"
  ],
  [
    "src/services/sfcdata.js~sfcdata#markup",
    "class/src/services/sfcData.js~SFCData.html#instance-get-markup",
    "src/services/sfcData.js~SFCData#markup",
    "member"
  ],
  [
    "src/services/sfcdata.js~sfcdata#modulescript",
    "class/src/services/sfcData.js~SFCData.html#instance-get-moduleScript",
    "src/services/sfcData.js~SFCData#moduleScript",
    "member"
  ],
  [
    "src/services/sfcdata.js~sfcdata#modulescripts",
    "class/src/services/sfcData.js~SFCData.html#instance-get-moduleScripts",
    "src/services/sfcData.js~SFCData#moduleScripts",
    "member"
  ],
  [
    "src/services/sfcdata.js~sfcdata#render",
    "class/src/services/sfcData.js~SFCData.html#instance-method-render",
    "src/services/sfcData.js~SFCData#render",
    "method"
  ],
  [
    "src/services/sfcdata.js~sfcdata#script",
    "class/src/services/sfcData.js~SFCData.html#instance-get-script",
    "src/services/sfcData.js~SFCData#script",
    "member"
  ],
  [
    "src/services/sfcdata.js~sfcdata#scripts",
    "class/src/services/sfcData.js~SFCData.html#instance-get-scripts",
    "src/services/sfcData.js~SFCData#scripts",
    "member"
  ],
  [
    "src/services/sfcdata.js~sfcdata#style",
    "class/src/services/sfcData.js~SFCData.html#instance-get-style",
    "src/services/sfcData.js~SFCData#style",
    "member"
  ],
  [
    "src/services/sfcdata.js~sfcdata#styles",
    "class/src/services/sfcData.js~SFCData.html#instance-get-styles",
    "src/services/sfcData.js~SFCData#styles",
    "member"
  ],
  [
    "src/services/sfcdata.js~sfcdata.new",
    "class/src/services/sfcData.js~SFCData.html#static-method-new",
    "src/services/sfcData.js~SFCData.new",
    "method"
  ],
  [
    "src/services/sfcparser.js",
    "file/src/services/sfcParser.js.html",
    "src/services/sfcParser.js",
    "file"
  ],
  [
    "src/services/sfcparser.js~sfcparser#constructor",
    "class/src/services/sfcParser.js~SFCParser.html#instance-constructor-constructor",
    "src/services/sfcParser.js~SFCParser#constructor",
    "method"
  ],
  [
    "src/services/sfcparser.js~sfcparser#parse",
    "class/src/services/sfcParser.js~SFCParser.html#instance-method-parse",
    "src/services/sfcParser.js~SFCParser#parse",
    "method"
  ],
  [
    "src/services/sfcparser.js~sfcparser#parsefrompath",
    "class/src/services/sfcParser.js~SFCParser.html#instance-method-parseFromPath",
    "src/services/sfcParser.js~SFCParser#parseFromPath",
    "method"
  ],
  [
    "src/typdef.js",
    "file/src/typdef.js.html",
    "src/typdef.js",
    "file"
  ],
  [
    "src/typdef.js~class",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes",
    "src/typdef.js~Class",
    "external"
  ],
  [
    "src/typdef.js~jimple",
    "https://yarnpkg.com/en/package/jimple",
    "src/typdef.js~Jimple",
    "external"
  ],
  [
    "src/typdef.js~provider",
    "typedef/index.html#static-typedef-Provider",
    "src/typdef.js~Provider",
    "typedef"
  ],
  [
    "src/typdef.js~providerregistermethod",
    "typedef/index.html#static-typedef-ProviderRegisterMethod",
    "src/typdef.js~ProviderRegisterMethod",
    "typedef"
  ],
  [
    "src/typdef.js~sfctag",
    "typedef/index.html#static-typedef-SFCTag",
    "src/typdef.js~SFCTag",
    "typedef"
  ],
  [
    "src/webpack.js",
    "file/src/webpack.js.html",
    "src/webpack.js",
    "file"
  ]
]