name: Release NPM package

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
        id: nvm
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
      - name: Install dependencies
        env:
          HUSKY: 0
        run: npm ci && npm i semantic-release@^21.0.7 @semantic-release/changelog@^6.0.3 @semantic-release/git@^10.0.1 -g
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Generate documentation
        run: npm run docs
      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: docs
