name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16', '18' ]
    name: Run jest and ESLint (Node ${{ matrix.node }})
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: cd examples/rollup && npm ci
      - run: cd examples/webpack && npm ci
      - run: npm run lint:all
      - run: npm test
      - name: Coveralls
        if: ${{ matrix.node == '18' }}
        uses: coverallsapp/github-action@v2
